#!/bin/bash
# (only to get syntax highlighting)
#

boot_pre() {

    # mount the API filesystem
    # /proc, /sys, /run, /dev, /run/lock, /dev/pts, /dev/shm
    echo_color 3 "stage: mounting API filesystem..."
    mountpoint -q /proc    || mount -t proc proc /proc -o nosuid,noexec,nodev
    mountpoint -q /sys     || mount -t sysfs sys /sys -o nosuid,noexec,nodev
    mountpoint -q /run     || mount -t tmpfs run /run -o mode=0755,nosuid,nodev
    mountpoint -q /dev     || mount -t devtmpfs dev /dev -o mode=0755,nosuid
    mkdir -p /dev/{pts,shm}
    mountpoint -q /dev/pts || mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
    mountpoint -q /dev/shm || mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

    # adaption: make /run/lock (Arch)
    mkdir -p -m 1777 /run/lock

}

boot_post() {

    # spawn gettys always
    echo_color 3 "stage: spawning gettys..."
    sh -c '/usr/bin/ubase/respawn -d 3 /usr/bin/agetty --noclear -8 -s 38400 tty1 linux' &
    sh -c '/usr/bin/ubase/respawn -d 3 /usr/bin/agetty -8 -s 38400 tty2 linux' &
    sh -c '/usr/bin/ubase/respawn -d 3 /usr/bin/agetty -8 -s 38400 tty3 linux' &
    sh -c '/usr/bin/ubase/respawn -d 3 /usr/bin/agetty -8 -s 38400 tty4 linux' &

}
